### ISSUE TITLE
Maximum call stack exceeded in Select.js

### ISSUE THREAD

**Issue by vsukhomlinov** [multiformats/js-multistream#5]
Code in src/lib/interactive.js can crash with the "Maximum call stack exceeded" exception

Test:
```
test('Crash emulation', function(done) {
    var select = new MultiStream.Select()
    tcp.createServer(function (socket) {
      select.handle(socket)
    }).listen(8012)

    var socket = tcp.connect({port:8012}, function tcpConnectionOpen() {
      lpm.write(socket, PROTOCOLID+'\n')
      var i=0;
      while(i++<100000) {
        lpm.write(socket, 'ls\n')
      }
    })
  })
```

**Comment by vsukhomlinov** [comment]
A ES6 generator is probably the best replacement for the current logic. Or at least that recursive call need to be wrapped into process.nextTick().

**Comment by vsukhomlinov** [comment]
@diasdavid Any plans to support native ES6 promises and eventually switch to promise-based logic? Or should I just patch the current logic using nextTick()?

**Comment by diasdavid** [comment]
We will be continuing use the callback pattern as the base, a promise API can be built on top, but breaking completely the current API is out of the table. 

On using process.nextTick(), that is fine, as long as we don't browser compatibility (certainly there is a shim for that functionality somewhere)

**Comment by diasdavid** [comment]
No longer applies with the new version coming with https://github.com/multiformats/js-multistream/pull/19 :)
